#!/bin/bash

LOG_FILE="safe_copy.log"
OPERATION="$1"
SOURCE_FILE="$2"
DESTINATION_PATH="$3"
USER_SELECTED_RESOLUTION=""
OPERATION_PERFORM_STATUS=""

#size in KB
SOURCE_FILE_SIZE=0
DIRECTORY_MAX_SIZE=1000
DESTINATION_AVAILABLE_SPACE_BEFORE=0
DESTINATION_AVAILABLE_SPACE_AFTER=0

